### PR TITLE
v1.3rc2 (v1.3rc1) bump

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR bumps the `spaghetti` version from `1.2` to `1.3rc1`.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

<code>@<space/>conda-forge-admin, please rerender</code>

### CODE REVIEW

**Comment by jGaboardi** [comment]
<code>@<space/>conda-forge-admin, please rerender</code>

**Comment by jGaboardi** [comment]
[Azure build failing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=35026&view=logs&jobId=e018f978-a0ce-53fb-9fb6-ffd586bfca01&taskId=2e5085ab-c8db-53b1-698d-462b17aa434f&lineStart=395&lineEnd=455&colStart=1&colEnd=36) with: 
`FileNotFoundError: [Errno 2] No such file or directory: 'requirements_dev.txt'`

-----------------------------
Full message:
```bash
Processing $SRC_DIR
  Created temporary directory: /tmp/pip-req-build-1tmv7pac
  Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-3r6unboe'
    Running command python setup.py egg_info
    Running setup.py (path:/tmp/pip-req-build-1tmv7pac/setup.py) egg_info for package from file://$SRC_DIR
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-1tmv7pac/setup.py", line 90, in <module>
        setup_package()
      File "/tmp/pip-req-build-1tmv7pac/setup.py", line 52, in setup_package
        reqs = _get_requirements_from_files(_groups_files)
      File "/tmp/pip-req-build-1tmv7pac/setup.py", line 37, in _get_requirements_from_files
        with open(v, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements_dev.txt'
Cleaning up...
  Removing source in /tmp/pip-req-build-1tmv7pac
Removed file://$SRC_DIR from build tracker '/tmp/pip-req-tracker-3r6unboe'
Removed build tracker '/tmp/pip-req-tracker-3r6unboe'
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-1tmv7pac/
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 368, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 177, in prep_for_dist
    self.req.prepare_metadata()
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 539, in prepare_metadata
    self.run_egg_info()
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 617, in run_egg_info
    command_desc='python setup.py egg_info')
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-1tmv7pac/
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1477, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/feedstock_root/build_artifacts/spaghetti_1557850465749/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
```

**Comment by knaaptime** [comment]
Need to add reqs_dev to manifest?

**Comment by knaaptime** [comment]
A la https://github.com/pysal/segregation/pull/22#issuecomment-491963460

**Comment by jGaboardi** [comment]
Oh huh. I guess it's not in the manifest! How did the `conda-forge` `feedstock` render correctly for the initial `spaghetti v1.2` build? Any idea?

**Comment by knaaptime** [comment]
The original pr probably only included the standard requirements.txt in the recipe (which is included in manifest) ?

**Review by ocefpaf — APPROVED** [review]
LGTM but you'll need to wither wait for a new release that fixes the missing file or patch `setup.py`/

**Comment by jGaboardi** [comment]
pysal/spaghetti#277

**Comment by jGaboardi** [comment]
- [x] update version
- [x] update `sha256`

**Comment by jGaboardi** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
