### PR TITLE
version bump v1.4.1 --> 1.4.2

### PR DESCRIPTION
**Pull request by jGaboardi**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jGaboardi** [comment]
@conda-forge-admin, please rerender

**Comment by knaaptime** [comment]
i'm impressed you make it here before the release bot :P

**Review by knaaptime — APPROVED** [review]

**Comment by jGaboardi** [comment]
[failing for `pytest-runner`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=124481&view=logs&j=e018f978-a0ce-53fb-9fb6-ffd586bfca01&t=5c69329b-d947-5705-66b5-610e0963c1aa&l=490)

```
406    ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
407    ERROR: No matching distribution found for pytest-runner
```

Seems to be related to pydata/xarray#2641, pydata/xarray#2643

**Comment by jGaboardi** [comment]
Closing following #15

**Pull request closed without merging**
